# Numpy

Материалы:
* Макрушин С.В. "Лекция 1: Библиотека Numpy"
* https://numpy.org/doc/stable/user/index.html
* https://numpy.org/doc/stable/reference/index.html

## Задачи для совместного разбора

1. Сгенерировать двухмерный массив `arr` размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в диапазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида  $𝑎𝑥+𝑏$  так, что после нормализации максимальный элемент масcива будет равен 1.0, минимальный 0.0

In [4]:
import numpy as np

In [6]:
np.random.randint(0, 20, size = (4, 7))

array([[ 4, 10, 12, 18,  3,  0, 12],
       [ 0,  8,  6,  4,  2,  1, 11],
       [ 8, 17,  1, 10, 17,  6,  8],
       [ 7,  1,  9, 11,  6, 16, 11]])

2. Создать матрицу 8 на 10 из случайных целых (используя модуль `numpy.random`) чисел из диапозона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

In [7]:
np.random.randint(0, 10, size = (8, 10))

array([[3, 7, 9, 1, 9, 6, 9, 3, 2, 9],
       [7, 8, 9, 7, 8, 3, 1, 5, 3, 9],
       [1, 4, 2, 3, 9, 4, 1, 5, 4, 1],
       [1, 4, 7, 9, 4, 7, 6, 8, 7, 8],
       [0, 9, 4, 7, 8, 4, 5, 2, 4, 6],
       [6, 1, 2, 9, 6, 8, 1, 9, 0, 2],
       [5, 2, 4, 5, 9, 2, 1, 7, 5, 1],
       [9, 2, 8, 5, 1, 4, 7, 9, 6, 2]])

3. Найти евклидово расстояние между двумя одномерными векторами одинаковой размерности.

In [10]:
import matplotlib.pyplot as pl
from mpl_toolkits.mplot3d import Axes3D

4. Решить матричное уравнение `A*X*B=-C` - найти матрицу `X`. Где `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.

## Лабораторная работа №1

Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$. 

4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

5. Посчитайте, сколько уникальных рецептов находится в датасете.

6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

10. Выберите случайным образом и выведите информацию о 10 различных рецептах

11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

13. Выведите процент "простых" рецептов в датасете

14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.

In [2]:
#1.
import numpy as np

fname = 'data\minutes_n_ingredients.csv'
array = np.loadtxt(fname,dtype=np.int32,skiprows=1,max_rows=5,delimiter=',')
print(array)

[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 [ 67660      5      6]
 [157911     60     14]]


In [3]:
#2.
array = np.loadtxt(fname,dtype=np.int32,skiprows=1,usecols=(1,2), max_rows=5,delimiter=',')
middle=np.mean(array,axis=0)
mini=np.amin(array,axis=0)
maxi=np.amax(array,axis=0)
median=np.median(array,axis=0)
print('среднее  значение:',middle)
print('минимальное значение:',mini)
print('максимальное значение:',maxi)
print('медиана',median)

среднее  значение: [32.   9.8]
минимальное значение: [5 6]
максимальное значение: [60 16]
медиана [25.  7.]


In [4]:
#4.
array = np.loadtxt(fname,dtype=np.int32,skiprows=1,usecols=(1),delimiter=',')
ld = np.where(array==0)
correct_id=np.where(array==0,1,array)
print(correct_id,len(ld[0]))

[ 60  25  10 ...  65   5 140] 479


In [5]:
#5.
array = np.loadtxt(fname,dtype=np.int32,skiprows=1,usecols=0,delimiter=',')
origin = np.unique(array,axis=0)
len(origin)

100000

In [6]:
#6.
array = np.loadtxt(fname,dtype=np.int32,skiprows=1,usecols=2,delimiter=',')
array = np.unique(array,axis=0)

print(len(array),array)

37 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 37 39]


In [7]:
#7.
array = np.loadtxt(fname,dtype=np.int32,skiprows=1,usecols=2,delimiter=',')
array_too = np.loadtxt(fname,dtype=np.int32,skiprows=1,delimiter=',')
correct_id=np.where(array<=5)
array_too[tuple(map(tuple,correct_id ))]

array([[446597,     15,      5],
       [204134,      5,      3],
       [ 25623,      6,      4],
       ...,
       [ 52088,     60,      5],
       [128811,     15,      4],
       [370915,      5,      4]])

In [99]:
#8.
array = np.loadtxt(fname,dtype=np.int32,skiprows=1,delimiter=',')
cof = array[:,2]/array[:,1]
print(cof.max())
# присутствуют рецепты, время которых = 0 минут

inf


C:\Users\erzau\AppData\Local\Temp\ipykernel_14972\2129373227.py:3: RuntimeWarning: divide by zero encountered in true_divide
  cof = array[:,2]/array[:,1]


In [100]:
#9.
array = np.loadtxt(fname,dtype=np.int32,skiprows=1,delimiter=',')
rows = np.argsort(array[:,1])[-100:]
print(np.mean(array[rows,2]))


6.61


In [101]:
#10
print(array[np.random.choice(array.shape[0], 10, replace=False)])

[[328311     45     13]
 [197728    100      9]
 [159224    105     18]
 [161474     50     12]
 [ 65999      5      4]
 [111213     40     11]
 [120886     40     12]
 [444648     30     10]
 [ 89499      5      5]
 [163097    330     17]]


In [102]:
#11
print(len(array[array[:,2]<np.mean(array[:,2])])/len(array)*100,'%')

58.802 %


In [103]:
#12
el = (array[:,1]<=20) & (array[:,2]<=5)
print(np.insert(array,3,el,axis=1))

[[127244     60     16      0]
 [ 23891     25      7      0]
 [ 94746     10      6      0]
 ...
 [498432     65     15      0]
 [370915      5      4      1]
 [ 81993    140     14      0]]


13. Выведите процент "простых" рецептов в датасете

In [104]:

print(len(array[el])/len(array)*100,'%')

9.552 %


#14
Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.


In [106]:
temp = np.copy(array)
mask_short = temp[:,1] <= 10
mask_middle = (temp[:,1] > 10) & (temp[:,1] < 20)
mask_long = temp[:,1] >= 20
short = temp[mask_short]
middle = temp[mask_middle]
long = temp[mask_long]
res_size = min(len(short), len(middle), len(long))
res_array = np.array([short[:res_size], middle[:res_size], long[:res_size]])
print(np.shape(res_array))

(3, 7783, 3)
[[[ 94746     10      6]
  [ 67660      5      6]
  [366174      7      9]
  ...
  [  7983      0      6]
  [184171      5      2]
  [ 89181      5      7]]

 [[ 33941     18      9]
  [446597     15      5]
  [ 81006     12      7]
  ...
  [ 44120     17      5]
  [ 60756     15      5]
  [128811     15      4]]

 [[127244     60     16]
  [ 23891     25      7]
  [157911     60     14]
  ...
  [186515    220     11]
  [372540     50      6]
  [172926    120     13]]]
